-- MySQL Script generated by MySQL Workbench
-- Thu May 15 10:19:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuarios` INT NOT NULL,
  `empresa_id` INT NOT NULL,
  `nome_prato` VARCHAR(255) NOT NULL,
  `pratoscol` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `cidade_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publicacoes_usuarios1_idx` (`id_usuarios` ASC) VISIBLE,
  INDEX `fk_publicacoes_empresa1_idx` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicacoes_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicacoes_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `mydb`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reacoes_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reacoes_usuarios` (
  `id_usuarios` INT NOT NULL,
  `id_publicacoes` INT NOT NULL,
  `reacoes` ENUM("Like", "Dislike") NOT NULL,
  INDEX `fk_reacoes_publicacoes1_idx` (`id_publicacoes` ASC) VISIBLE,
  INDEX `fk_reacoes_usuarios1_idx` (`id_usuarios` ASC) VISIBLE,
  CONSTRAINT `fk_reacoes_publicacoes1`
    FOREIGN KEY (`id_publicacoes`)
    REFERENCES `mydb`.`publicacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reacoes_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_publicacao` INT NOT NULL,
  `comentarios` VARCHAR(255) NOT NULL,
  `data` DATETIME NOT NULL,
  `foto_perfil` VARCHAR(255) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `data_comentario` DATETIME NOT NULL,
  `comentarioscol` VARCHAR(45) NULL,
  `comentarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_comentarios_publicacoes1_idx` (`id_publicacao` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicacoes1`
    FOREIGN KEY (`id_publicacao`)
    REFERENCES `mydb`.`publicacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
